version: '3'
services:

  #PHP Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    tty: true
    command: "php artisan serve --host=0.0.0.0 --port=8000"
    environment:
      SERVICE_NAME: api
      CORS_MAX_AGE: 500
      SERVICE_TAGS: dev
      docker: "true"
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - kata-network

  # Front app
  app:
    container_name: app
    hostname: app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
      - '3003:3003'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - kata-network


  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lawsuits
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - kata-network

#Docker Networks
networks:
  kata-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
